CREATE TABLE ColProd
(Product# NUMBER NOT NULL,
Weight VARCHAR2(5),
PRIMARY KEY(Product#),
FOREIGN KEY(Product#)
REFERENCES Product
ON DELETE CASCADE);

INSERT INTO ColProd VALUES (4,'6.61');
INSERT INTO ColProd VALUES (5,'6.61');
INSERT INTO ColProd VALUES (6,'1.69');
INSERT INTO ColProd VALUES (7,'2.69');
INSERT INTO ColProd VALUES (10,'2.13');
INSERT INTO ColProd VALUES (11,'2.13');
