CREATE TABLE DelStaff
(Employee# INT NOT NULL,
PRIMARY KEY (Employee#),
FOREIGN KEY (Employee#)
REFERENCES Employee
ON DELETE CASCADE);

INSERT INTO DelStaff VALUES (2);
INSERT INTO DelStaff VALUES (5);
INSERT INTO DelStaff VALUES (8);
INSERT INTO DelStaff VALUES (11);
INSERT INTO DelStaff VALUES (14);
INSERT INTO DelStaff VALUES (17);
INSERT INTO DelStaff VALUES (20);
INSERT INTO DelStaff VALUES (23);
INSERT INTO DelStaff VALUES (26);
INSERT INTO DelStaff VALUES (29);
